recipe/0019-Use-XML_SetHashSalt-in-_elmenttree.patch
recipe/meta.yaml
recipe/run_test.py

Addresses security vulnerability: CVE-2018-14647
https://www.securityfocus.com/bid/105396/info 
Ref: https://github.com/python/cpython/commit/18b20bad75b4ff0486940fba4ec680e96e70f3a2

Add patch for python 2.7.15

---

recipe/0020-Add-CondaEcosystemModifyDllSearchPath.patch

@mingwandroid take a look as discussed

Fixed wchar_t string op issue

---

recipe/build_base.sh
recipe/meta.yaml
recipe/patches/0034-distutils-fix-ldshared.patch

Patch `0034-distutils-fix-ldshared.patch` comes from the Conda-Forge recipe.
Worked with @katietz to resolve build errors on OSX.

Update to v3.9.6

---

README.anaconda.md
README.md

Adds instructions to the README on how to validate that new python builds are working properly.
Not 100% sure this is the ideal place for this so let me know.

Adding instructions on how to test python

---

recipe/meta.yaml

- Updating SHA
- changing build # back to 0
- updating version number

updating to 3.8.15

---

recipe/brand_python.py
recipe/meta.yaml

**Jira:** [PKG-1058](https://anaconda.atlassian.net/browse/PKG-1058)
**Updates:**
- bumped build number
- Changed message to: "packaged by Anaconda, Inc."

PKG-1058 Fix Branding 3.9

---

recipe/brand_python.py
recipe/meta.yaml

**Jira:** [PKG-1060](https://anaconda.atlassian.net/browse/PKG-1060)
**Updates:**
- bumped build number
- Changed message to: "packaged by Anaconda, Inc."

PKG-1060 Fix branding 3.11

---

abs.yaml
recipe/meta.yaml
recipe/patches/0010-Unvendor-openssl.patch
recipe/patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
recipe/patches/0022-Unvendor-tcltk.patch

Changes:
- Update to 3.11.2, reset build number to 0
- Adjust patches
https://github.com/python/cpython/tree/v3.11.2
https://www.python.org/downloads/release/python-3112/
abs.yaml to be removed before merging.

PKG-1243 Update to 3.11.2

---

abs.yaml
recipe/meta.yaml
recipe/patches/0010-Unvendor-openssl.patch

Creating a Python that uses OpenSSL 3.

Python 3.11 Openssl3 py311 build [skip ci]

---

recipe/meta.yaml
recipe/patches/0010-Unvendor-openssl.patch
recipe/patches/0026-Use-OpenSSL-3-instead-of-1_1.patch

Changes:
- Update to 3.11.4
https://docs.python.org/release/3.11.4/whatsnew/changelog.html#python-3-11-4

Update to 3.11.4

---

recipe/meta.yaml
recipe/patches/0015-Unvendor-openssl.patch
recipe/patches/0016-Unvendor-sqlite3.patch

Changes:
- Update to 3.9.17
https://docs.python.org/release/3.9.17/whatsnew/changelog.html#python-3-9-17

Update to 3.9.17

---

recipe/meta.yaml
recipe/patches/0017-Unvendor-openssl.patch
recipe/patches/0018-Unvendor-sqlite3.patch
recipe/patches/0034-Use-OpenSSL-3-instead-of-1_1.patch

Changes:
- Update to 3.8.17
https://docs.python.org/release/3.8.17/whatsnew/changelog.html#python-3-8-17

Update to 3.8.17

---

recipe/build_base.sh
recipe/build_static.sh

Changes:
- add cd ${SRC_DIR} to build.sh

PKG-2507_2

---

recipe/meta.yaml

Changes:
- Update to 3.10.13
https://docs.python.org/release/3.10.13/whatsnew/changelog.html#python-3-10.13

Update to 3.10.13

---

recipe/meta.yaml

Changes:
- Update to 3.9.18
https://docs.python.org/release/3.9.18/whatsnew/changelog.html#python-3-9-18

Update to 3.9.18

---

recipe/meta.yaml

Changes:
- Update to 3.8.18
https://docs.python.org/release/3.9.18/whatsnew/changelog.html#python-3-8-18

Update to 3.8.18

---

abs.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml
recipe/patches/0005-Unvendor-openssl.patch

Changes:
- Update to 3.12.0
https://www.python.org/downloads/release/python-3120/
https://github.com/python/cpython/compare/v3.12.0rc3...v3.12.0

Update to 3.12.0

---

recipe/meta.yaml
recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
recipe/patches/0010-Unvendor-openssl.patch
recipe/patches/0016-cross-compile-darwin.patch
recipe/patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch

Python 3.11.7
**Destination channel:**  defaults
- [PKG-3026](https://anaconda.atlassian.net/browse/PKG-3026?atlOrigin=eyJpIjoiY2I5YjUzMGUxYTcyNGViYzk0NzdkN2IyOThlZmRjOTgiLCJwIjoiaiJ9) 
- [Upstream repository](https://github.com/python/cpython)
- [Upstream changelog/diff](https://github.com/python/cpython/compare/v3.11.5...v3.11.7)
- Update from v3.11.5 to v3.11.7
[PKG-3026]: https://anaconda.atlassian.net/browse/PKG-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update to 3.11.7

---

recipe/meta.yaml
recipe/patches/0010-Unvendor-openssl.patch

python 3.11.8
- [PKG-4026](https://anaconda.atlassian.net/browse/PKG-4026)
- [Upstream repository](https://www.python.org/)
- [Upstream changelog/diff](https://docs.python.org/release/3.11.8/whatsnew/changelog.html)
- Update version and sha256
- update `openssl` and `zlib` versions
[PKG-4026]: https://anaconda.atlassian.net/browse/PKG-4026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Version 3.11.8

---

recipe/meta.yaml
recipe/patches/0010-Unvendor-openssl.patch

python 3.10.14
- [PKG-4309](https://anaconda.atlassian.net/browse/PKG-4309)
- [Upstream repository](https://www.python.org/downloads/release/python-31014/)
- [Upstream changelog/diff](https://docs.python.org/release/3.10.14/whatsnew/changelog.html)
- Update version
- Update `openssl` and `zlib` versions
[PKG-4309]: https://anaconda.atlassian.net/browse/PKG-4309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Version 3.10.14

---

recipe/meta.yaml

rebuild for codesign

---

recipe/meta.yaml

- [PKG-5670](https://anaconda.atlassian.net/browse/PKG-5670)
- [Upstream repository](https://www.python.org/downloads/release/python-31015/)
- [Upstream changelog/diff](https://docs.python.org/release/3.10.15/whatsnew/changelog.html#python-3-10-15)
- No changes
-
[PKG-5670]: https://anaconda.atlassian.net/browse/PKG-5670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

python 3.10.15

---

recipe/meta.yaml

- [PKG-6414](https://anaconda.atlassian.net/browse/PKG-6414)
- [Upstream repository](https://devguide.python.org/)
- [Upstream changelog/diff](https://docs.python.org/release/3.9.21/whatsnew/changelog.html)
- Version update
[PKG-6414]: https://anaconda.atlassian.net/browse/PKG-6414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

python 3.9.21

---

recipe/meta.yaml

- [PKG-6412](https://anaconda.atlassian.net/browse/PKG-6412)
- [Upstream repository](https://devguide.python.org/)
- [Upstream changelog/diff](https://docs.python.org/release/3.10.16/whatsnew/changelog.html)
- Version update
[PKG-6412]: https://anaconda.atlassian.net/browse/PKG-6412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

python 3.10.16

---

recipe/meta.yaml

- [PKG-6416](https://anaconda.atlassian.net/browse/PKG-6416)
- [Upstream repository](https://devguide.python.org/)
- [Upstream changelog/diff](https://docs.python.org/release/3.13.1/whatsnew/changelog.html)
- Version update
[PKG-6416]: https://anaconda.atlassian.net/browse/PKG-6416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

python 3.13.1

---

recipe/meta.yaml

- [PKG-7002](https://anaconda.atlassian.net/browse/PKG-7002) 
- Simple version and SHA update
[PKG-7002]: https://anaconda.atlassian.net/browse/PKG-7002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

python 3.13.2

---

recipe/meta.yaml

- [PKG-7003](https://anaconda.atlassian.net/browse/PKG-7003) 
- version and sha update only required
[PKG-7003]: https://anaconda.atlassian.net/browse/PKG-7003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

python 3.12.9 PKG-7003
