AnacondaRecipes/python-feedstock

- recipe/meta.yaml
- recipe/patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
There were some reported issues with packages being unable to correctly use `find_library()`. This patch has been updated to be the same as what Conda-Forge uses: [see here](https://github.com/conda-forge/python-feedstock/blob/3.8/recipe/patches/0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch)
I believe the error originates from around the return statements of `_findLib_prefix()`.
> Python v3.8.8 build 1

- recipe/build_base.bat
- recipe/meta.yaml
- recipe/patches/0017-Unvendor-openssl.patch
Updated build_base.bat and meta.yaml
python 3.8.12 was tested by running commands:
`$ python -i`
```
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import re
>>> import sys
>>> import math
```
The standard http server doesn't throw errors: `python -m http.server --bind 127.0.0.1`.
`conda-build` built successfully `pyarrow` a python dependent package with this version of python
> Update to 3.8.12

- recipe/meta.yaml
- recipe/patches/0003-Support-cross-compiling-byte-code.patch
- recipe/patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
- recipe/patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0011-Unvendor-sqlite3.patch
- recipe/patches/0012-venv-Revert-a-change-from-https-github.com-python-cp.patch
- recipe/patches/0018-cross-compile-darwin.patch
- recipe/patches/0026-unvendor-zlib.patch
This updates Python 3.10.0 to 3.10.3:
Updated sources and hashes
Rebased patches
This is to be merged only after conda-package-handling has been upgraded to version 1.8.0.
> Python 3.10.3

- recipe/build_base.bat
- recipe/meta.yaml
- recipe/patches/0004-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0005-Support-cross-compiling-byte-code.patch
- recipe/patches/0007-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
- recipe/patches/0008-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
- recipe/patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
- recipe/patches/0011-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
- recipe/patches/0013-Fix-cross-compilation-on-Debian-based-distros.patch
- recipe/patches/0014-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0015-Unvendor-openssl.patch
- recipe/patches/0016-Unvendor-sqlite3.patch
- recipe/patches/0017-venv-Revert-a-change-from-https-github.com-python-cp.patch
- recipe/patches/0020-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0024-Add-CONDA_DLL_SEARCH_MODIFICATION_KEEP_GIL-to-aid-de.patch
- recipe/patches/0025-cross-compile-darwin.patch
- recipe/patches/0032-Fix-TZPATH-on-windows.patch
- recipe/patches/9999-Add-Anaconda-Distribution-version-logic.patch
This upgrades Python 3.9.7 to 3.9.11.
Updated sources and hashes
Rebased patches
Updated cpython-source-deps for Windows builds
> Python 3.9.11

- recipe/build_base.bat
- recipe/meta.yaml
- recipe/patches/0002-Add-Anaconda-Distribution-version-logic.patch
- recipe/patches/0006-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0007-Support-cross-compiling-byte-code.patch
- recipe/patches/0009-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
- recipe/patches/0012-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
- recipe/patches/0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0015-Fix-cross-compilation-on-Debian-based-distros.patch
- recipe/patches/0017-Unvendor-openssl.patch
- recipe/patches/0018-Unvendor-sqlite3.patch
- recipe/patches/0022-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0024-cross-compile-darwin.patch.patch
- recipe/patches/0032-ctypes-link-to-coreFoundation.patch
This upgrades Python 3.8.12 to 3.8.13.
Updated sources and hashes
Rebased patches
Updated cpython-source-deps for Windows builds
> Python 3.8.13

- recipe/meta.yaml
- recipe/patches/0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0017-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0018-Unvendor-openssl.patch
- recipe/patches/0019-Unvendor-sqlite3.patch
- recipe/patches/0021-Add-CondaEcosystemModifyDllSearchPath.patch
This upgrades Python 3.7.11 to 3.7.13.
Updated sources and hashes
Rebased patches
Updated cpython-source-deps for Windows builds
> Upgrade to Python 3.7.13

- recipe/meta.yaml
This is a quick and easy upgrade from 3.10.3 to 3.10.4. All patches apply cleanly, no changes necessary.
> Update to Python 3.10.4

- recipe/meta.yaml
Patch level version update from 3.9.11 to 3.9.12. All patches apply cleanly.
Release notes:
https://docs.python.org/release/3.9.12/whatsnew/changelog.html
> Python 3.9.12

- recipe/meta.yaml
Update to `v3.9.15` to get latest security fixes (primarily for CVE-2020-10735).
Release notes: https://docs.python.org/release/3.9.15/whatsnew/changelog.html
Also includes fix for [CVE-2020-10735](https://nvd.nist.gov/vuln/detail/CVE-2020-10735), which was addressed in `v3.9.14` (see [release notes](https://docs.python.org/release/3.9.14/whatsnew/changelog.html)).
> Update to v3.9.15

- recipe/meta.yaml
- recipe/patches/0011-Unvendor-sqlite3.patch
- [Jira issue](https://anaconda.atlassian.net/browse/PKG-874)
- [Upstream repository](https://github.com/python/cpython/tree/3.10)
- [Changelog/diff](https://github.com/python/cpython/compare/v3.10.8...v3.10.9)
- [Related PR(s)]()
- [Python 3.9.16](https://github.com/AnacondaRecipes/python-feedstock/pull/91)
- [Python 3.8.16](https://github.com/AnacondaRecipes/python-feedstock/pull/90)
- [Python 3.7.16](https://github.com/AnacondaRecipes/python-feedstock/pull/89)
--------------------
Updates to `python 3.10.9`
- Update version and SHA
- Update `011-Unvendor-sqlite3.patch` to match modified upstream source
> Python 3.10.9

- recipe/meta.yaml
- [Jira issue](https://anaconda.atlassian.net/browse/PKG-875)
- [Upstream repository](https://github.com/python/cpython/tree/3.9)
- [Changelog/diff](https://github.com/python/cpython/compare/v3.9.15...v3.9.16)
- [Related PR(s)]()
- [Python 3.10.9](https://github.com/AnacondaRecipes/python-feedstock/pull/92)
- [Python 3.8.16](https://github.com/AnacondaRecipes/python-feedstock/pull/90)
- [Python 3.7.16](https://github.com/AnacondaRecipes/python-feedstock/pull/89)
--------------------
Updates to `python 3.9.16`
- MailCap CVE-2015-20107 [was fixed upstream](https://github.com/python/cpython/commit/c59a16e2c7495a90e6d23a48ec98623f3fb1e176)
- Update version and SHA
- Disable `CVE-2015-20107` patch
> Python 3.9.16

- recipe/meta.yaml
- recipe/patches/0018-Unvendor-openssl.patch
- [Jira issue](https://anaconda.atlassian.net/browse/PKG-877)
- [Upstream repository](https://github.com/python/cpython/tree/3.7)
- [Changelog/diff](https://github.com/python/cpython/compare/v3.7.15...v3.7.16)
- [Related PR(s)]()
- [Python 3.9.16](https://github.com/AnacondaRecipes/python-feedstock/pull/91)
- [Python 3.10.16](https://github.com/AnacondaRecipes/python-feedstock/pull/92)
- [Python 3.8.16](https://github.com/AnacondaRecipes/python-feedstock/pull/90)
--------------------
Updates to `python 3.7.16`
- MailCap CVE-2015-20107 [was fixed upstream](https://github.com/python/cpython/commit/6e8e9e7c030b6236ff220362944cba1b93c84bc4)
- Update version and SHA
- Disable `CVE-2015-20107` patch
- Fix `0018-Unvendor-openssl.patch` to look for DLLs with suffix `-1_1-x64.dll` on windows-64. …
> Python 3.7.16

- recipe/meta.yaml
- [Jira issue](https://anaconda.atlassian.net/browse/PKG-876)
- [Upstream repository](https://github.com/python/cpython/tree/3.8)
- [Changelog/diff](https://github.com/python/cpython/compare/v3.8.15...v3.8.16)
- [Related PR(s)]()
- [Python 3.9.16](https://github.com/AnacondaRecipes/python-feedstock/pull/91)
- [Python 3.10.9](https://github.com/AnacondaRecipes/python-feedstock/pull/92)
- [Python 3.7.16](https://github.com/AnacondaRecipes/python-feedstock/pull/89)
--------------------
Updates to `python 3.8.16`
- MailCap CVE-2015-20107 [was fixed upstream](https://github.com/python/cpython/commit/0a4f650347fdcfd82d094ab2134ca89584f4e877)
- Update version and SHA
- Disable `CVE-2015-20107` patch
> Python 3.8.16

- recipe/brand_python.py
- recipe/build_base.sh
- recipe/meta.yaml
**Jira:** [PKG-1057](https://anaconda.atlassian.net/browse/PKG-1057)
**Updates:**
- bumped build number
- Changed message to: "packaged by Anaconda, Inc."
- Changing the test argument in [build_base.sh](https://github.com/AnacondaRecipes/python-feedstock/pull/96/files#diff-e0638ff31f64a715c0ed3faa90c7b9f61ef3ff28d4a622e89e31923e585394bb) to use `--pgo` instead of `--pgo-extended` because it was causing our `linux-64` build to stall (following [Conda-Forge's approach](https://github.com/conda-forge/python-feedstock/blame/main/recipe/build_base.sh#L280-L284))
> PKG-1057 Fix Branding 3.8

- abs.yaml
- recipe/meta.yaml
- Updated build number
- Updated abs.yaml so it will go to openssl3 channel
- Modified recipe to not depend on cmake which requires openssl 1.1.1
> Python 3.10 build for OpenSSL 3 [skip ci]

- abs.yaml
- recipe/meta.yaml
- recipe/patches/0036-openssl3.patch
- recipe/run_test.py
- Updated build number
- Updated recipe to not use cmake dependent on openssl
- Updated abs.yaml to go to specific channel
> Python 3.9 build for OpenSSL 3 [skip ci]

- recipe/meta.yaml
Changes:
- Update to 3.12.0 beta 4
- Update pins in host section
- Remove libffi from run (handle through run_exports, like other deps)
- Remove extra license_url
https://github.com/python/cpython/compare/v3.12.0b3...v3.12.0b4
Note: this gets uploaded to ad-testing/label/py312 on merge.
> Update to 3.12.0b4

- recipe/meta.yaml
- recipe/patches/0010-Unvendor-openssl.patch
- recipe/patches/0017-Fix-TZPATH-on-windows.patch
- recipe/patches/0022-Unvendor-tcltk.patch
Changes:
- Update to 3.12.0 rc 2
- Update patch
- Restore patch header #121
python/cpython@v3.12.0rc1...v3.12.0rc2
Note: this gets uploaded to ad-testing/label/py312 on merge.
> Update to 3.12.0rc2

- recipe/meta.yaml
- recipe/patches/0005-Unvendor-openssl.patch
python 3.12.2
- [PKG-4027](https://anaconda.atlassian.net/browse/PKG-4027)
- [Upstream repository](https://www.python.org/downloads/release/python-3122/)
- [Upstream changelog/diff](https://docs.python.org/release/3.12.2/whatsnew/changelog.html#python-3-12-2)
- Update version and `sha256`
- Update `openssl` and `zlib` versions
[PKG-4027]: https://anaconda.atlassian.net/browse/PKG-4027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 3.12.2

- recipe/meta.yaml
- recipe/patches/0005-Unvendor-openssl.patch
- [PKG-5058](https://anaconda.atlassian.net/browse/PKG-5058)
- [Upstream repository](https://www.python.org/downloads/release/python-3124/)
- [Upstream changelog/diff](https://docs.python.org/release/3.12.4/whatsnew/changelog.html#python-3-12-4)
- Set version and sha256
- Update sqlite version in openssl patch
[PKG-5058]: https://anaconda.atlassian.net/browse/PKG-5058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> python 3.12.4

- recipe/meta.yaml
- recipe/patches/0005-Unvendor-openssl.patch
- [PKG-5750](https://anaconda.atlassian.net/browse/PKG-5750)
- [Upstream repository](https://www.python.org/downloads/release/python-3126/)
- [Upstream changelog/diff](https://docs.python.org/release/3.12.6/whatsnew/changelog.html#python-3-12-6)
- Refresh [0005-Unvendor-openssl.patch](https://github.com/AnacondaRecipes/python-feedstock/pull/155/files#diff-010853d569985a92365d1a248f3a7e4ba5f4b354c651a779b52b0f7ae7688726)
[PKG-5750]: https://anaconda.atlassian.net/browse/PKG-5750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> python 3.12.6

- recipe/meta.yaml
- recipe/patches/0010-Unvendor-openssl.patch
- [PKG-5672](https://anaconda.atlassian.net/browse/PKG-5672)
- [Upstream repository](https://www.python.org/downloads/release/python-31110/)
- [Upstream changelog/diff](https://docs.python.org/release/3.11.10/whatsnew/changelog.html#python-3-11-10)
- Refresh 0010-Unvendor-openssl.patch and add `+  <Target Name="_DummyTarget">` to fix an error during patching 
-
[PKG-5672]: https://anaconda.atlassian.net/browse/PKG-5672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> python 3.11.10

- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/tests/cmake/run_cmake_test.bat
- [PKG-5671](https://anaconda.atlassian.net/browse/PKG-5671)
- [Upstream repository](https://www.python.org/downloads/release/python-3920/)
- [Upstream changelog/diff](https://docs.python.org/release/3.9.20/whatsnew/changelog.html#python-3-9-20)
- Remove vs2017 and vc14 from the local cbc.yaml because our current base cbc.yaml uses vs2019.
- Use `Ninja` as a `CMake Generator` to fix an error:
```
(%PREFIX%) %SRC_DIR%\tests\cmake>cmake -G"Visual Studio 16 2019 Win64" -DPY_VER=3.9.20 --debug-find .
Running with debug output on for the `find` commands.
(%PREFIX%) %SRC_DIR%\tests\cmake>if 1 NEQ 0 exit /b 1
```
Other Python variants rely on `ninja-base` in the test environment and it's already available [there](https://github.com/AnacondaRecipes/python-feedstock/pu …
> python 3.9.20

- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/0035-do-not-override-win-sdk.patch
- [PKG-5669](https://anaconda.atlassian.net/browse/PKG-5669)
- [Upstream repository](https://www.python.org/downloads/release/python-3820/)
- [Upstream changelog/diff](https://docs.python.org/release/3.8.20/whatsnew/changelog.html#python-3-8-20)
- Use vs2019 in a local cbc.yaml
- **cpython 3.8** hardcodes using the sdk version out of caution:
`<_RegistryVersion Condition="$([System.Version]::Parse($(_RegistryVersion))) >= $([System.Version]::Parse(`10.0.22000.0`))">10.0.19041.0</_RegistryVersion>`
It causes an error:
`     2>C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.19041.0 was not found. Install the required version of Windows …
> python 3.8.20

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
python 3.13.0
- https://anaconda.atlassian.net/browse/PKG-5843
- https://github.com/python/cpython/tree/v3.13.0
- https://github.com/python/cpython/compare/v3.13.0rc3...v3.13.0
- https://docs.python.org/release/3.13.0/whatsnew/changelog.html#python-3-13-0
- https://docs.python.org/3.13/whatsnew/3.13.html
- The freethreading variant will be built in a subsequent PR.
> update to 3.13.0

- recipe/meta.yaml
- [PKG-6413](https://anaconda.atlassian.net/browse/PKG-6413)
- [Upstream repository](https://devguide.python.org/)
- [Upstream changelog/diff](https://docs.python.org/release/3.11.11/whatsnew/changelog.html)
- Version update
[PKG-6413]: https://anaconda.atlassian.net/browse/PKG-6413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> python 3.11.11

- recipe/build_base.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
- recipe/patches/0002-Win32-Do-not-download-externals.patch
- recipe/patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
- recipe/patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
- recipe/patches/0005-Unvendor-openssl.patch
- recipe/patches/0006-Unvendor-sqlite3.patch
- recipe/patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
- recipe/patches/0008-Doing-d1trimfile.patch
- recipe/patches/0009-Allow-cross-compiling-for-Darwin.patch
- recipe/patches/0010-Fix-TZPATH-on-windows.patch
- recipe/patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
- recipe/patches/0012-Unvendor-bzip2.patch
- recipe/patches/0013-Unvendor-libffi.patch
- recipe/patches/0014-Unvendor-tcltk.patch
- recipe/patches/0015-unvendor-xz.patch
- recipe/patches/0016-unvendor-zlib.patch
- recipe/patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
- recipe/patches/0018-Unvendor-expat.patch
- recipe/patches/0019-Remove-unused-readelf.patch
- recipe/patches/0021-Override-configure-LIBFFI.patch
- recipe/patches/0022-Unvendor-libmpdec.patch
- recipe/patches/0023-branding.patch
- recipe/patches/0024-Unvendor-zlib-ng.patch
- recipe/patches/0025-Unvendor-zstd.patch
- recipe/sitecustomize.py
python 3.14.0rc3 
**Destination channel:** Defaults
- [PKG-9706]
- dev_url:        https://devguide.python.org/
- conda_forge:    https://github.com/conda-forge/python-feedstock
- pypi:           https://pypi.org/project/python/3.14.0rc3
- pypi inspector: https://inspector.pypi.io/project/python/3.14.0rc3
- new version number
- add CF's `conda-site.pth` patch for non-`win`
- add @M-Waszkiewicz-Anaconda 's suggestion so that the `python-{freethreading,gil}` metapackages successfully depend on the `rcN` releases! 🫰 
Most recent build graph: https://package-build.anaconda.com/v1/graph/fd12d298-f2df-4182-a9c0-8c0c70faf52d
[PKG-9706]: https://anaconda.atlassian.net/browse/PKG-9706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> python 3.14.0rc3 
